### ISSUE TITLE
Roadmap to 1.0 beta

### ISSUE THREAD

**Issue by TheSonAlsoRises** [porygonco/porybox#174]
Back end:
- [x] set up the server
- [x] create the main page
- [x] fix the Fateful encounter flag
- [x] change format of response so that pk6 comes up as a download instead of a string

Front end:
- [x] make the box settings come up in a modal
- [x] Pokémon settings (#205)
- [x] display Pokémon notes (dependent on #205)
- [x] moving Pokémon around a box (#20)
- [ ] account settings (#13)
- [x] user page
- [x] add download link for public Pokémon
- [x] populate the main page (#160, #282)
- [x] provide feedback to user when a pk6 is uploaded
- [x] provide additional feedback (failed upload, invalid pk6, upload to other box) (#283)
- [x] multiple file uploads / drag and drop (#132)
- [x] add a token description for Box 1 (#196)
- [x] update on-site docs
- [x] finish footer

Other:
- [x] pk6parse: region names
- [x] pk6parse: memories
- [x] pk6parse: move power
- [x] add CONTRIBUTING.md

On top of everything listed in the 1.0 beta milestone.

**Comment by YaManicKill** [comment]
Account settings won't be done for 1.0 beta.
